create table if not exists public.productos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  categoria text not null,
  precio numeric not null,
  stock integer not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  email_usuario text,
  creado_en timestamp with time zone default now(),
  actualizado_en timestamp with time zone
);

alter table public.productos enable row level security;

create policy "usuarios leen sus productos"
on public.productos for select
to authenticated
using (auth.uid() = user_id);

create policy "usuarios crean sus productos"
on public.productos for insert
to authenticated
with check (auth.uid() = user_id);

create policy "usuarios actualizan sus productos"
on public.productos for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "usuarios eliminan sus productos"
on public.productos for delete
to authenticated
using (auth.uid() = user_id);
